Flexberry/ember-flexberry-gis

addon/components/flexberry-layerstree.js, addon/components/flexberry-layerstreenode.js, addon/components/flexberry-tree.js, addon/components/flexberry-treenode.js, addon/mixins/flexberry-layerstree-component.js, addon/mixins/flexberry-layerstreenode-actions-handler.js, addon/templates/components/flexberry-layerstree.hbs, addon/templates/components/flexberry-layerstreenode.hbs, addon/templates/components/flexberry-treenode.hbs, app/components/flexberry-layerstree.js, app/components/flexberry-layerstreenode.js, tests/dummy/app/controllers/application.js, tests/dummy/app/controllers/components-examples/flexberry-layerstree/settings-example.js, tests/dummy/app/locales/en/translations.js, tests/dummy/app/locales/ru/translations.js, tests/dummy/app/router.js, tests/dummy/app/routes/components-examples/flexberry-layerstree/settings-example.js, tests/dummy/app/templates/components-examples/flexberry-layerstree/settings-example.hbs, tests/dummy/app/views/components-examples/flexberry-layerstree/settings-example.js
TFS#105911
Add components flexberry-layerstree and flexberry-layerstreenode based on flexberry-tree and flexberry-treenode and used for layers structures.
=> Map layers tree

addon/styles/addon.scss, addon/styles/components/flexberry-button.scss, addon/styles/components/flexberry-map.scss, addon/styles/components/flexberry-tree.scss, addon/styles/components/layer-result-list.scss, addon/styles/components/map-commands-dialogs/search.scss
Fixed checkboxes in tree
Removed useless selectors that had no influence on markup
Removed unecessary !important's
Code is written in SASS way
=> Refactored styles

addon/map-tools/base-nonclickable.js, addon/map-tools/draw.js, addon/map-tools/identify.js, addon/map-tools/measure.js, app/map-tools/base-nonclickable.js
Fixed doubleClickZoom on draw and measure ending for map tools
=> Disable doubleClickZoom on draw/measure tools activation

addon/components/layers/geocoder-base-layer.js, addon/components/layers/wfs-layer.js, addon/map-tools/identify.js, tests/dummy/app/controllers/map.js
Refactored due to kuzkok's remarks
=> Refactored identification area to L.Polygon

addon/components/base-layer.js, addon/components/flexberry-map.js, addon/components/layer-result-list.js, addon/components/layers/geocoder-base-layer.js, addon/components/layers/wfs-layer.js, addon/components/layers/wms-layer.js, addon/components/layers/wms-wfs-layer.js, addon/map-tools/identify.js, addon/mixins/regenerated/models/new-platform-flexberry-g-i-s-layer-link.js, addon/mixins/regenerated/models/new-platform-flexberry-g-i-s-map-layer.js, addon/mixins/regenerated/models/new-platform-flexberry-g-i-s-map.js, addon/templates/components/layer-result-list.hbs, vendor/flexberry/models/new-platform-flexberry-g-i-s-layer-link.json
Rafectoring feature methods according to search method pattern. Added auto-expand in layer-result-list for first and only result
=> Refactoring identify search query results

addon/components/minimap-control.js
More options to setup this control
=> Added more native options for minimap control

addon/components/base-layer.js
filter layerlink in base layer by its MOS
=> Added unified layerLinks filter for query

addon/components/flexberry-maplayer.js, addon/components/legends/base-legend.js, addon/templates/components/flexberry-layerslegends.hbs, addon/templates/components/flexberry-maplayer.hbs
Added lazy loading of legends, only when treenode had been expanded once
=> Added lazy loading for layer's legends

addon/mixins/flexberry-maplayer-actions-handler.js
Previous sorting order method had many wasteful operations, so it is refactored and fixed
=> Fixed sorting order (index recomputing)

addon/helpers/header-from-projection.js, addon/routes/gis-search-form.js, addon/templates/components/flexberry-table.hbs, app/helpers/get-field.js, app/helpers/header-from-projection.js, app/templates/gis-search-form.hbs
Add helper that returns an object composed of model fields and their names in accordance with the projection and current locale.
=> Feature 150466 header from projection helper

addon/components/flexberry-map.js, addon/components/layers-dialogs/edit-modes/base.js, addon/components/layers/wfs-layer.js, addon/map-tools/identify.js
Leaflet has changed defaults for layers, so I returned previous appearance
Fixed edit-modes parent's binding as now there are one more component between (flexberry-edit-layermap inside edit-/add-dialog
=> Identify search layers style

addon/components/layer-result-list.js
Changes for observer initialization.
=> layer esult list

addon/components/flexberry-layers-attributes-panel.js, addon/components/geometry-add-modes/geoprovider.js, addon/components/geometry-add-modes/manual.js, addon/geo-providers/base.js, addon/geo-providers/yandex-maps-geocoder.js, addon/locales/en/components/geometry-add-modes.js, addon/locales/en/components/geometry-add-modes/geoprovider.js, addon/locales/en/components/geometry-add-modes/manual.js, addon/locales/en/translations.js, addon/locales/ru/components/geometry-add-modes.js, addon/locales/ru/components/geometry-add-modes/geoprovider.js, addon/locales/ru/components/geometry-add-modes/manual.js, addon/locales/ru/translations.js, addon/styles/themes/default/globals/site.variables, addon/styles/themes/default/modules/modal.overrides, addon/templates/components/geometry-add-modes/geoprovider.hbs, addon/templates/components/geometry-add-modes/manual.hbs, app/geo-providers/base.js, app/geo-providers/yandex-maps-geocoder.js, tests/dummy/app/styles/app.less, tests/integration/components/flexberry-layers-attributes-panel-test.js
Add yandex geocoder as geoprovider.
=> Feature 149901 wfs layer editing

addon/components/charts/type-charts/base-chart-type.js, addon/components/charts/type-charts/column.js, addon/components/charts/type-charts/line.js, addon/components/charts/type-charts/pie.js, addon/components/flexberry-layers-attributes-panel.js, addon/templates/components/flexberry-layers-attributes-panel.hbs, app/components/charts/type-charts/base-chart-type.js
Выполнены задачи по диаграммам (пункт 1.b из письма).
Диаграмма теперь строится по выделенным записям или по всем, если записи не выделены.
Также исправлена ошибка при формировании списка полей для выпадающего списка компонента диаграмм.
=> Fix chart issues

addon/components/flexberry-layers-attributes-panel.js, addon/mixins/flexberry-maplayer-actions-handler.js, addon/templates/components/flexberry-layers-attributes-panel.hbs, tests/dummy/app/controllers/map.js, tests/dummy/app/templates/map.hbs
Добавил крутилку на панель атрибутов, пока вкладка загружается.
=> Feature show dimmer while attributes tab is loading

addon/components/base-layer.js, addon/templates/components/flexberry-layers.hbs, tests/integration/components/flexberry-layers-test.js
Добавил отправку экшенов из компонента слоя на создание и удаление.
На них можно подписаться через dynamic actions и делать некую обработку нужного слоя на прикладной стороне.
=> Feature actions on layer init and destroy

.jscsrc, addon/components/layers-dialogs/group/tab/identification-settings.js, addon/locales/en/components/layers-dialogs/settings.js, addon/locales/ru/components/layers-dialogs/settings.js, addon/templates/components/layers-dialogs/group/display.hbs, addon/templates/components/layers-dialogs/group/tab/identification-settings.hbs, app/components/layers-dialogs/group/tab/identification-settings.js, tests/integration/components/layers-dialogs/group/tab/identification-settings-test.js
@DubrovinPavel How should it be exactly refactored: in which folder should I put the component? Or should the whole tab be as a single component?
=> Add identification-settings component

CHANGELOG.md, addon/components/base-vector-layer.js, addon/mixins/geojson-filter-parser.js, app/components/base-vector-layer.js, tests/unit/components/base-vector-layer-test.js
TFS [#159326](http://dis-tfs:8080/Common/CASEBERRY/_workitems/edit/159326).
=> Identification on layers with multigeometries

addon/components/charts/base-chart-type.js, addon/components/charts/index-chart.js, addon/components/charts/type-charts/bar.js, addon/components/charts/type-charts/line.js, addon/components/charts/type-charts/pie.js, addon/locales/en/components/charts/index-chart.js, addon/locales/ru/components/charts/index-chart.js, addon/templates/components/charts/index-chart.hbs
=> Add grouping for diagrams

addon/components/base-vector-layer.js, addon/utils/leaflet-opacity.js, app/utils/leaflet-opacity.js, tests/dummy/config/environment.js, tests/unit/utils/leaflet-opacity-test.js
Не знаю какой способ лучше: явно задать значения и перерисовать или сохранять старый стиль и использовать setStyle
=> Add geometries opacity change

addon/mixins/leaflet-zoom-to-feature.js
=> Fix zoomTo feature

addon/components/flexberry-map.js, addon/mixins/flexberry-map-model-api.js, addon/routes/edit-map.js
Fixed error with showing subset of objects in layer
=> refactor '_setVisibilityObjects'

tests/dummy/app/controllers/map.js
Удаление случайно попавших в прошлый коммит неиспользуемых свойств
=> refactor map controller

addon/components/base-layer.js, addon/components/flexberry-map.js, addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js, vendor/api-tests/api-test-map.html
The function of loading layers on the map.
=> Feature 194144 ready layers map 2

addon/components/flexberry-layers-attributes-panel.js, addon/locales/en/components/map-tools.js, addon/locales/ru/components/map-tools.js, addon/templates/components/flexberry-layers-attributes-panel.hbs, addon/templates/components/geometry-add-modes/draw.hbs
=> Feature 188690 edit partial geometries tools 2

addon/mixins/flexberry-map-model-api.js
fix error in API getLayerObjectOptions and getIntersectionObjects
=> fix error in API getLayerObjectOptions and getIntersectionObjects

addon/mixins/flexberry-map-model-api.js
Добавил проекции в методы. Как оказалось turf/booleanContains не работает с этими чертовыми мультиполигонами, пока что сделал так чтобы сравнивались, первые полигоны из мультиполигонов, надо подумать как будет лучше сделать
=> fixed 'isContainsObject', 'getAreaExtends'

addon/mixins/flexberry-map-model-api.js
=> Feature fix error snapshot

addon/mixins/flexberry-map-actions-handler.js, addon/mixins/flexberry-map-model-api-visualedit.js, addon/mixins/flexberry-map-model-api.js
Feature get layer model public
=> Feature get layer model public

addon/components/flexberry-layers-attributes-panel.js
feature 193458 edit spatial data
=> Feature 193458 edit spatial

addon/components/flexberry-layers-intersections-panel.js, addon/styles/themes/blue-sky/elements/button.overrides, addon/styles/themes/blue-sky/globals/site.overrides, addon/templates/components/flexberry-layers-intersections-panel.hbs
=> Fix intersection panel layout

addon/components/base-layer.js, addon/components/base-vector-layer.js, addon/components/layers/wfs-layer.js, addon/mixins/flexberry-map-actions-handler.js, addon/mixins/flexberry-map-model-api-savelayer.js, addon/mixins/flexberry-map-model-api-visualedit.js
if to finish editing correctly it works well
=> feature CancelEdit

addon/components/flexberry-edit-layermap.js, addon/components/layers-dialogs/add.js, addon/components/layers-dialogs/edit.js, addon/components/layers-dialogs/tabs/load-file.js, addon/components/layers-dialogs/tabs/main.js, addon/locales/en/components/layers-dialogs/add.js, addon/locales/en/components/layers-dialogs/edit.js, addon/locales/ru/components/layers-dialogs/add.js, addon/locales/ru/components/layers-dialogs/edit.js, addon/styles/themes/default/modules/modal.overrides, addon/templates/components/flexberry-edit-layermap.hbs, addon/templates/components/layers-dialogs/edit.hbs, addon/templates/components/layers-dialogs/tabs/load-file.hbs, addon/templates/components/layers-dialogs/tabs/main.hbs, app/components/layers-dialogs/tabs/load-file.js
=> feature 193460 import rastr

addon/components/flexberry-layers-attributes-panel.js, addon/locales/ru/components/map-tools.js, addon/templates/components/flexberry-layers-attributes-panel.hbs
Поправил ошибки по задачке 188690
https://dis-dev-ops/Common/RGISPermKrai/_workitems/edit/188690
=> Fix 188690 edit spatial data

addon/components/base-layer.js
displaying a layer when visibility is enabled at the desired zoom level and the data has not yet been loaded
=> visibility layer

addon/components/geometry-add-modes/import.js, addon/templates/components/geometry-add-modes/import.hbs
Исправлено:
1.При подгрузке данных из файла появляется окошко (скрин ниже), при нажатии на выпадашку, появляются значения атрибутов слоя, но так же появляются и пустые значения
2. Когда выбрано значение, выпадашка закрывается и выпадает снова.
=> removed empty values in dropdown

addon/components/geometry-add-modes/rhumb.js, addon/locales/en/components/geometry-add-modes/rhumb.js, addon/locales/ru/components/geometry-add-modes/rhumb.js, addon/styles/themes/default/elements/container.overrides, addon/templates/components/flexberry-layers-attributes-panel.hbs, addon/templates/components/geometry-add-modes/rhumb.hbs, tests/integration/components/flexberry-layers-attributes-panel-test.js
-Добавлено поле для ввода системы координат
-Добавлен дополнительный столбец в таблицу румбов. 
-Реализована возможность редактирования данных внутри таблицы румбов
-Реализована возможность формирования полигона начиная не с первого румба, а пропуская произвольное количество румбов в начале.
=> visual changes in rhumb creation tool

.jshintrc, addon/components/geometry-add-modes/manual.js, addon/locales/en/components/geometry-add-modes/manual.js, addon/locales/ru/components/geometry-add-modes/manual.js, addon/templates/components/geometry-add-modes/manual.hbs
Исправлено:
1.Конкретизировать ошибки по вводу координат. 
2.Блокировка полей
Немного поправил верстку, расположил дропдауны с crs и geometry в одну строку
=> edit hbs file, added specific error messages, crs

addon/mixins/flexberry-map-model-api-savelayer.js
Исправлено: 
После изменения гео-объекта и его сохранения идет дублироние объекта на карте
=> remove prev feature before load changed

addon/components/feature-result-item.js, addon/components/flexberry-layers-intersections-panel.js, addon/components/flexberry-multiple-select.js, addon/components/layer-result-list.js, addon/initializers/leaflet-marker.js, addon/locales/en/components/flexberry-layers-intersections-panel.js, addon/locales/ru/components/flexberry-layers-intersections-panel.js, addon/mixins/flexberry-map-model-api.js, addon/styles/themes/blue-sky/globals/site.overrides, addon/styles/themes/default/globals/site.overrides, addon/templates/components/flexberry-layers-intersections-panel.hbs, addon/templates/components/flexberry-multiple-select.hbs, addon/templates/components/layer-result-list.hbs
Исправление ошибок в апи для работы с маркерами.
Исправление ошибок зума для маркера.
Исправление ошибок инструмента поиска пересечений.
=> fix error crs for point object, zoom marker

addon/components/geometry-add-modes/rhumb.js, addon/components/layers-dialogs/add.js, addon/locales/en/components/geometry-add-modes/rhumb.js, addon/locales/ru/components/geometry-add-modes/rhumb.js, addon/styles/themes/blue-sky/modules/modal.overrides, addon/templates/components/flexberry-layers-attributes-panel.hbs, addon/templates/components/geometry-add-modes/rhumb.hbs
Исправление инструмента создания объекта по румбам
=> feature 193382 rhumbs

addon/components/layers/wfs-layer.js, addon/mixins/flexberry-map-model-api.js
проблема с методом апи "Отображение/ скрытие подмножества объектов слоя" он отрабатывает только в случае если слой предварительно был включен
=> Fix error show object

addon/components/layers/wfs-layer.js, addon/mixins/flexberry-map-model-api-visualedit.js, addon/mixins/flexberry-map-model-api.js
fix error show layer object and continueLoading()
=> fix error show layer object

addon/components/layers/wfs-layer.js, addon/utils/check-zoom.js, package.json
Change Ember.get to native properties
Init minZoom and maxZoom on layer load
=> Fix map freeze

addon/components/layers/wfs-layer.js, addon/components/map-commands-dialogs/export.js, addon/initializers/leaflet-marker.js, addon/mixins/flexberry-map-model-api-savelayer.js, addon/mixins/flexberry-map-model-api.js, addon/mixins/leaflet-zoom-to-feature.js, addon/utils/check-zoom.js, addon/utils/html2canvas-clone.js, app/utils/html2canvas-clone.js
1. экспорт в рисунок 
2. приближение к объекту не с тем масштабом 
3. подвисание при редактировании объектов с большим количеством точек
4. Апи сохранения при выключенном слое
5. Поиск по атрибутам в wfs слое
=> fix error version 20200427

addon/mixins/leaflet-zoom-to-feature.js
=> fix error zoom

addon/components/layers/odata-vector-layer.js
=> modify set properties

addon/components/feature-export.js, addon/components/flexberry-layers-attributes-panel.js, addon/components/layers/odata-vector-layer.js, addon/mixins/flexberry-map-model-api.js, addon/styles/themes/default/elements/container.overrides, tests/dummy/config/environment.js
Исправлена выгрузка одата слоев в СК МСК-59 и mif.
Ошибка при построении объекта с дыркой. 
Удаление объектов одата-слоев из панели атрибутов.
Исправлена ошибка инструмент "Поиск пересечения" для одата слоев.
=> fix error version

.travis.yml, addon/components/layers/wfs-layer.js
Реализация and/or условий в linkParameters. Дать возможность указать переход по нескольким альтернативным вариантам
=> And or linkparameter

addon/components/feature-export.js, addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js
fix bug zoom,
error export kml
=> fix bug zoom, error export

addon/components/layers/odata-vector-layer.js
modify return value from save method
=> modify return value from save method

addon/components/base-layer.js, addon/components/base-vector-layer.js, addon/components/layers/geojson-layer.js, addon/components/layers/kml-layer.js, addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js, addon/mixins/flexberry-map-actions-handler.js, addon/mixins/flexberry-map-model-api-visualedit.js, addon/styles/addon.less
Reverts Flexberry/ember-flexberry-gis#362
=> Revert "Порядок слоев"

addon/mixins/flexberry-map-model-api.js
modify api getIntersectObjects
=> modify api getIntersectObjects

addon/components/layers/odata-vector-layer.js, addon/mixins/flexberry-map-model-api-visualedit.js
ошибка в cancelEdit после addObjectToLayer
=> ошибка в cancelEdit после addObjectToLayer

addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js, app/gis-browserify.js, package.json
Динамическая загрузка с использованием мультиполигонах для odata и  wfs слоев
=> Динамическая загрузка с использованием мультиполигонах

addon/mixins/flexberry-map-model-api.js, tests/unit/models/new-platform-flexberry-g-i-s-map-test.js
modify api getIntersectionArea
=> Wi modify get intersection area

addon/mixins/flexberry-map-model-api.js
Получать координаты первого объекта перед циклом
=> fix error coord first object

addon/components/base-vector-layer.js, addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js, addon/mixins/flexberry-map-model-api.js, addon/utils/feature-with-area-intersect.js, app/utils/feature-with-area-intersect.js, package.json, tests/dummy/config/environment.js, tests/unit/components/base-vector-layer-test.js, yarn.lock
modify  api getIntersectionObjects that return area intersection
=> Wi modify get intersection objects

addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js
Исправление ошибки загрузки объектов, если они уже все загружены
=> Исправление ошибки загрузки объектов, если они уже все загружены

addon/components/layers/odata-vector-layer.js, addon/utils/feature-with-area-intersect.js, package.json, tests/dummy/config/environment.js, yarn.lock
=> returned request on identify

package.json
=> return packages

addon/adapters/odata.js, addon/components/layers/odata-vector-layer.js, app/adapters/odata.js, package.json
Изменение вычитки и сохранения одата объектов через batch запрос
=> Fix error bbox

addon/components/layers/wfs-layer.js, addon/utils/feature-with-area-intersect.js
=> intesectArea only polygon

addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js, addon/utils/feature-with-area-intersect.js
ошибка при удаление только что созданный объект - он не удалялся из массива на сохранение
=> Fix error version 20200716

addon/components/layers/odata-vector-layer.js, addon/utils/feature-with-area-intersect.js, tests/dummy/config/environment.js
=> fix error IntesectionArea

addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js
=> fix error loaded objects

addon/components/layers/odata-vector-layer.js
fix error delete and add callback for save
=> fix error delete and add callback for save

addon/components/base-vector-layer.js, addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js
Удаление надписи при удалении объекта;
Применение функций к надписям
=> fix error labels

addon/components/base-layer.js, addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js, tests/dummy/app/adapters/application.js, tests/unit/components/layers/odata-vector-layer-test.js
Для теста ошибки, вынесла адаптер в переменные, потому что даже с помощью Олега не получается пропихать нужный адаптер. Лукап заменила на adapterFor - сказали так правильнее
=> fix error load all object in odata

addon/components/layers/wfs-layer.js, addon/initializers/leaflet.js, addon/mixins/flexberry-map-model-api-expansion.js, addon/mixins/flexberry-map-model-api.js, addon/utils/feature-with-area-intersect.js, tests/unit/mixins/map-model-api-getlayerobjectoptions-test.js
Turf calc area with approximate formula - it is not good. Change all area calculation to use jsts library.
Add helper functions toProjectedGeoJSON to leaflet vector classes.
=> Change area calculation to use jsts

addon/components/base-vector-layer.js, addon/components/layers/odata-vector-layer.js, addon/mixins/flexberry-map-model-api-expansion.js, addon/mixins/flexberry-map-model-api-visualedit.js, addon/mixins/flexberry-map-model-api.js, tests/unit/mixins/flexberry-map-model-api-expansion-add-object-to-layer-test.js
Fix addObjectToLayer method, fix returning new objects in odata-vector-layer, fix init labels zoom
=> fix adding objects to layer

addon/components/layers/odata-vector-layer.js
=> fix save odata

addon/components/flexberry-map.js, addon/components/geometry-add-modes/rhumb.js, addon/locales/en/components/geometry-add-modes/rhumb.js, addon/locales/ru/components/geometry-add-modes/rhumb.js, addon/mixins/flexberry-map-model-api-expansion.js, addon/mixins/flexberry-map-model-api.js, addon/templates/components/geometry-add-modes/rhumb.hbs, addon/utils/rhumb-operations.js, tests/unit/mixins/flexberry-map-model-api-create-polygon-object-rhumb-test.js, tests/unit/mixins/flexberry-map-model-api-get-rhumb-test.js
Change api getRhumb.
Adding param editable in flexberry-map. Enabling map editing by default.
Fixing english name for direction of rhumb.
=> change api getRhumb

addon/components/geometry-add-modes/rhumb.js, addon/mixins/flexberry-map-model-api-expansion.js, addon/utils/rhumb-operations.js, app/gis-browserify.js, package.json, tests/unit/mixins/flexberry-map-model-api-create-polygon-object-rhumb-test.js, tests/unit/utils/rhumb-operations-test.js, yarn.lock
Object by rhumb is created in crs of layer.
Added documentation for createPolygonObjectRhumb.
Removed turf from createObjectRhumb
=> fix createRhumb

addon/adapters/odata.js, addon/components/base-layer.js, addon/components/base-vector-layer.js, addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js, addon/mixins/flexberry-map-model-api-reloadlayer.js, addon/models/new-platform-flexberry-g-i-s-map.js, tests/unit/components/layers/odata-vector-layer-test.js
=> layer reload

addon/components/layers/odata-vector-layer.js, addon/initializers/leaflet-ewkt.js, addon/mixins/flexberry-map-model-api-cosmos.js, addon/models/new-platform-flexberry-g-i-s-map.js, addon/utils/get-crs-by-name.js, addon/utils/layer-to-ewkt.js, app/gis-browserify.js, app/initializers/leaflet-ewkt.js, app/utils/get-crs-by-name.js, app/utils/layer-to-ewkt.js, package.json, tests/dummy/config/environment.js, tests/unit/components/layers/odata-vector-layer-test.js, tests/unit/mixins/flexberry-map-model-api-cosmos-test.js, tests/unit/utils/get-crs-by-name-test.js, tests/unit/utils/layer-to-ewkt-test.js
added leaflet function toEWKT
added api findCosmos
refactoring in Odate using toEWKT
=> Wi 207466 api find cosmos

addon/components/base-vector-layer.js
parsing labels using jquery instead of slow DOMParser
=> parsing labels using jquery instead of slow DOMParser

addon/components/base-vector-layer.js
=> fix error parsing labels

addon/components/base-layer.js, addon/components/base-vector-layer.js, addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js, addon/mixins/flexberry-map-model-api.js, tests/unit/components/layers/odata-vector-layer-test.js, tests/unit/mixins/flexberry_map_model_api_show_and_hide_test.js
show and hide layers return prmise, 
fix state in odata after save
=> show and hide layers as odata, fix state in odata after save

addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js, addon/mixins/flexberry-map-model-api.js, tests/unit/components/layers/odata-vector-layer-test.js
=> Fix error clear layers

addon/components/base-vector-layer.js
fixed error adding labels for non-dynamic layers
=> fixed error adding labels for non-dynamic layers

addon/components/base-vector-layer.js
fixing error displaying line labels when zooming
=> fixing error displaying line labels when zooming

addon/mixins/flexberry-map-model-api-cosmos.js, tests/unit/mixins/flexberry-map-model-api-cosmos-test.js
added api addLayerFromLayerMetadata and tests for it
=> added api addLayerFromLayerMetadata and tests for it

addon/components/feature-export.js, addon/mixins/flexberry-map-model-api-cosmos.js, addon/mixins/flexberry-map-model-api.js, addon/utils/download-file.js, addon/utils/get-crs-by-name.js, app/utils/download-file.js, tests/unit/mixins/flexberry-map-model-api-download-file-test.js, tests/unit/utils/download-file-test.js, tests/unit/utils/get-crs-by-name-test.js
added util downloadFile, that is used in mapApi downloadFile and feature-export, and test for them
=> added api downloadFile

addon/components/layers/wfs-layer.js, addon/mixins/flexberry-map-model-api.js, tests/unit/mixins/flexberry_map_model_api_show_and_hide_test.js
Теперь _setVisibility для слоев !showExisting $$ !continueLoading работает без загрузки данных
=> Рефакторинг _setVisibility

addon/initializers/leaflet-marker.js
=> Теперь если иконка назначена она не будет заменена

addon/mixins/flexberry-map-model-api.js, tests/unit/mixins/flexberry-map-model-api-set-visibilitty-test.js, tests/unit/mixins/flexberry-map-model-api-set-visibility-objects-test.js, tests/unit/mixins/flexberry-map-model-apit-set-visibilitty-test.js
Теперь setVisibility будет работать со слоями showExisting = true
=> Убрал из условия showExisting

addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js, addon/initializers/leaflet-marker.js, addon/layers/tile-vector.js, addon/mixins/flexberry-map-model-api.js, tests/unit/components/layers/odata-vector-layer-test.js, tests/unit/mixins/flexberry-map-model-api-set-visibilitty-test.js, tests/unit/mixins/flexberry_map_model_api_show_and_hide_test.js
При сохранении слоя, удалялся объект слоя, но не его надписи. Теперь удаляются и надписи.
=> Добавил удаление надписей

addon/components/flexberry-create-object-geometry.js, addon/components/flexberry-layers-attributes-panel.js, addon/components/layers-dialogs/attributes/edit.js, addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js
Fixed errors:
- label does not appear when adding feature
- after edited feature properties, label's text don't change
- don't save wfs layer
- for odata: after edited feature properties, button 'Save' don't available
- for odata: buffer is not being built
- changes Ember.copy on Object.assign because properties are copied incorrectly (a lot of extra)
=> fix error attr panel

addon/components/layers-dialogs/edit.js
fix error open dialog edit layer
=> fix error open dialog edit layer

addon/components/geometry-add-modes/manual.js
fix negative coordintates and reprojection CRS
=> fix negative coordintates and reprojection CRS

addon/components/layers/wfs-layer.js, addon/mixins/flexberry-map-model-api.js, tests/unit/components/layers/wfs-layer-test.js, tests/unit/mixins/flexberry-map-model-api-copy-objects-test.js
copyObjects -> copyObjectsBatch
properties -> withProperties 
Также создается пустое поле .feature = { properties: {} }; для дальнейшего добавления объектов в слой
=> Исправил название + изменил поле

addon/components/flexberry-layers-attributes-panel.js, addon/components/geometry-add-modes/manual.js, addon/mixins/flexberry-maplayer-actions-handler.js
Исправлена ошибка: получить координаты только что созданного объекта.
Исправлена ошибка: после сохранения в панели атрибутов, для wfs слоя пропадает объект
=> Fix add by coord

addon/mixins/flexberry-map-model-api-expansion.js, addon/mixins/flexberry-map-model-api.js
=> _getMulti return Multi object

addon/components/layers/odata-vector-layer.js, addon/layers/odata-vector.js, addon/mixins/odata-filter-parser.js, tests/unit/mixins/odata-filter-parser-test.js
=> adds odata filter

addon/components/geometry-add-modes/manual.js, addon/locales/en/components/geometry-add-modes/manual.js, addon/locales/ru/components/geometry-add-modes/manual.js, addon/templates/components/geometry-add-modes/manual.hbs
1. Correct caption path for objectType
2. Error message about count of points for type geometry
3. Clear dialog after close
=> fix error create on coordinates

addon/components/geometry-add-modes/import.js, addon/mixins/flexberry-map-model-api.js, tests/unit/mixins/flexberry-map-model-api-test.js
=> fix for migration on netcore

addon/components/flexberry-search-panel.js, addon/locales/en/components/flexberry-search.js, addon/locales/ru/components/flexberry-search.js, addon/styles/themes/default/elements/container.overrides, addon/styles/themes/default/modules/search.overrides, addon/styles/themes/default/modules/sidebar.overrides, addon/templates/components/flexberry-search-panel.hbs, tests/dummy/app/controllers/map.js, tests/dummy/app/templates/map.hbs
Rebrand search: merge context search, search by attributem, go to coordinate
=> rebrand search

addon/components/flexberry-maplayer.js, addon/controllers/edit-map.js, addon/mixins/flexberry-layers-action-handler.js, addon/models/new-platform-flexberry-g-i-s-map-layer.js, tests/dummy/app/templates/map.hbs
Add mixin for flexberry-layers action, and handle onLayerInit in it. Set property layerInitialized for layer model and check this property on layer tree render
=> Add layerInit handler

addon/adapters/odata.js, addon/components/flexberry-map.js, addon/components/flexberry-maplayer.js, addon/mixins/flexberry-map-model-api-visualedit.js, tests/dummy/app/templates/map.hbs, vendor/api-tests/api-test-map.html
Fixs error leafletmap substitution
=> Feature 215893 leafletmap substitution

addon/utils/create-layer-from-metadata.js, tests/unit/mixins/flexberry-map-model-api-cosmos-test.js
Added parameter id on layerModel when createLayerFromMetadata is launch.
Added test on method createLayerFromMetadata.
=> task 190 + tests

addon/components/flexberry-edit-layer-feature.js, addon/components/layers-dialogs/attributes/edit.js, addon/templates/components/flexberry-edit-layer-feature.hbs, addon/templates/components/layers-dialogs/attributes/edit.hbs, bower.json
replace semantic_ui_daterangepicker on daterangepicker
replace flexberr-datepicker on flexberry-simpledatetime
=> replace semantic_ui_daterangepicker on daterangepicker

addon/components/layers-dialogs/add.js, addon/components/map-tools/background-layers.js, addon/mixins/flexberry-map-model-api-cosmos.js, addon/mixins/flexberry-maplayer-actions-handler.js, addon/styles/themes/default/elements/container.overrides, addon/styles/themes/default/modules/sidebar.overrides, addon/utils/change-index-on-map-layers.js, tests/unit/mixins/flexberry-map-model-api-cosmos-test.js
1) теперь слой метаданных при добавлении через апи показывается в дереве слоев;
2) можно добавлять слои в дерево;
3) добавил условие при добавлении слоев:
3.1) если это подложка то она добавляется в hierarchy и в backgrooundLayers
3.2) если это слой то он добавляется в hierarchy и otherLayers;
=> Now metadata layers visible on tree

addon/mixins/leaflet-map/map-sidebar.js, tests/dummy/app/controllers/map.js
Изменил функции hide() и show().
Добавил в них вызов функции onToggleButtonClick.
=> Add show or hide sidebar

addon/components/base-vector-layer.js, addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js, addon/mixins/flexberry-map-model-api-savelayer.js, tests/unit/components/layers/odata-vector-layer-test.js, tests/unit/components/layers/wfs-layer-test.js
Process layer.feature.geometry when editLayer call
=> fix edit layer

addon/components/flexberry-search-panel.js, tests/integration/components/flexberry-search-panel-test.js
output when go to through coordinates in degrees min sec
=> output when go to through coordinates in degrees min sec, add tests

addon/components/flexberry-layers-attributes-panel.js
=> fix edit layer settings

addon/components/feature-result-item.js, addon/components/flexberry-edit-layer-feature.js, addon/mixins/favorites-features.js, tests/dummy/app/templates/map.hbs, tests/unit/mixins/favorites-features-test.js
Add event updateFavorite. This event is fire when edited feature already saved.
Add function _updateFavorite. This function needed to update favorite feature.
=> Update edited feature

tests/dummy/app/controllers/map.js
fixed the error of binding the layer visibility switching event
=> fixed the error of binding the layer visibility switching event

CHANGELOG.md, addon/components/flexberry-layers-attributes-panel.js, addon/styles/themes/blue-sky/modules/sidebar.overrides, addon/styles/themes/default/elements/container.overrides, tests/unit/components/flexberry-layers-attributes-panel-test.js
1) Fix style minus icon
2) Fix style .ui.pointing.group.secondary.menu
3) Now check all it's worked on attributes panel
4) Added test on method changeSelectedAll
=> fix changeSelectedAll + check style

addon/components/flexberry-layers-attributes-panel.js, tests/unit/components/flexberry-layers-attributes-panel-test.js
=> fix changeSelectedAll

addon/styles/themes/default/elements/container.overrides
Added margin-top on icon minus in identify panel.
=> Update style on icon minus

CHANGELOG.md, addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js, addon/mixins/flexberry-map-model-api.js, tests/unit/mixins/flexberry_map_model_api_show_and_hide_test.js
Changed:
1) ContinueLoad with showExisting layers (odata-vector/wfs).
2) ShowAllLayerObjects doesn't clear objects on layer if showExitsting = true.
=> Changed continueLoad with showExisting

addon/components/layers/odata-vector-layer.js, addon/components/layers/wfs-layer.js
Add condition if is empty then loaded
=> Add condition if is empty then loaded

CHANGELOG.md, addon/components/feature-result-item.js, addon/components/flexberry-identify-panel.js, addon/components/flexberry-maplayer.js, addon/styles/themes/blue-sky/elements/container.overrides, addon/styles/themes/blue-sky/elements/list.overrides, addon/styles/themes/blue-sky/modules/sidebar.overrides, addon/styles/themes/default/elements/container.overrides, addon/styles/themes/default/modules/sidebar.overrides, addon/utils/open-close-sub-menu.js
Added:
* if sub menu on feature-result-item after showing lower than main menu buttons then sub menu moving up.
Updated:
* icon on indetify panel: rectangle and broken line.
* height on list of feature in identify panel.
=> Fix style on icon if identify panel

CHANGELOG.md, addon/components/feature-result-item.js, addon/components/flexberry-maplayer.js, addon/components/layers/wfs-layer.js, addon/utils/open-close-sub-menu.js, tests/unit/components/layers/wfs-layer-test.js
1) add pane adn renderer on every objects in layer WFS if layer showExisting = true
=> fixed error: layer showexisting ignore zoom

CHANGELOG.md, addon/components/base-vector-layer.js, addon/components/feature-result-item.js, addon/components/flexberry-maplayer.js, addon/components/layers/wfs-layer.js, addon/instance-initializers/precision-scale.js, addon/mixins/flexberry-map-model-api-expansion.js, addon/utils/layer-to-jsts.js, addon/utils/open-close-sub-menu.js, app/instance-initializers/precision-scale.js, tests/unit/components/base-vector-layer-test.js
Added reducer on utils/layer-to-jsts. This is need because data equals topology errors and isValid doesn't check that.
=> add geometry reducer

addon/components/layers/odata-vector-layer.js
some changes to createa multiply layers with one dynamic model
=> odata-cluster-layer

CHANGELOG.md, addon/initializers/leaflet-jsts.js, addon/mixins/flexberry-map-model-api-expansion.js, addon/mixins/flexberry-map-model-api.js, addon/utils/layer-to-jsts.js, tests/unit/models/new-platform-flexberry-g-i-s-map-test.js, tests/unit/utils/layer-to-jsts-test.js
Added:
- geometryPrecisionReducer in functions utils/layer-to-jsts
- constant scale on mapApi
=> Add geometry reducer on layer-to-jsts
